### ISSUE TITLE
Suggestion: use description rather than name for readable description

### ISSUE THREAD

**Issue by shadowspawn** [TerribleDev/example-ts-cli#3]
The current code has:

```js
const program = new Command('Our New CLI');
```

This means the help looks like:
```
% terribledev --help

Usage: Our New CLI [options] [command]
```

But the installed command name is `terribledev`? 

I suggest either leave out the program "name", or specify it as "terribledev". It you leave it blank you get behaviour which works for the installed/linked command but guesses wrong for other invocations:

```
const program = new Command();
```

```
% terribledev --help

Usage: terribledev [options] [command]
...

% node dist/index.js --help

Usage: index [options] [command]
...
```

**Comment by shadowspawn** [comment]
Context: I saw your blog about Commander mentioned in https://nodeweekly.com/issues/447

I thought it was a nice article. Just passing on some minor suggestions!

**Comment by shadowspawn** [comment]
The  `.description()` is a good place to put the text:

```
program.description('Our New CLI');
```

and the help looks like
```
% terribledev -h

Usage: terribledev [options] [command]

Our New CLI

Options:
  -v, --verbose   verbose logging
  -V, --version   output the version number
  -h, --help      display help for command
...
```

**Comment by TerribleDev** [comment]
definitely!
