### ISSUE TITLE
.argument() parameter syntax not as expected by Commander

### ISSUE THREAD

**Issue by shadowspawn** [TerribleDev/example-ts-cli#4]
`.argument()` takes a first parameter which is expected to be either `<ARG>` or `[ARG]`. There isn't space in the parameter for leading words describing the argument.

So `.argument("widget id <id>", "the id of the widget")` is not fully recognised and works due to some fallback behaviour. You can tell things are a little awry from the usage, see the dubious `<widget id <id>>`.

```
% terribledev widgets get --help

Usage: terribledev widgets get [options] <widget id <id>>

Arguments:
  widget id <id>         the id of the widget
...
```

That should be just `.argument("<id>", "the id of the widget")`.

**Comment by TerribleDev** [comment]
Thanks so much @shadowspawn. This was a lot of simplifying a bigger project, so obviously I got some things wrong. I've added all the fixes you filed.
